<?php

namespace AppBundle\Repository;

/**
 * ExpositionQualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefaultShopValueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDefultValue($client_id,$brand_id,$header)
    {
        
        $query = $this->createQueryBuilder('c');
               // $query = $query->getQuery();
               $query->select('c.shopsGPV,c.shopsHQ');
                $query->where('c.brand=  :brand_id');
                $query->setParameter('brand_id', $brand_id);

                $query->andWhere('c.client =  :client');
                $query->setParameter('client', $client_id);

                $query->andWhere('c.header =  :header');
                $query->setParameter('header', $header);
                $query = $query->getQuery();

                return $query->getOneOrNullResult();
       
        
    }

    public function getAll()
    { 
        return $this->createQueryBuilder('c')
                    ->getQuery()
                    ->getResult();
    }

}
