<?php

namespace AppBundle\Repository;

/**
 * ExpositionQualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpositionQualityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        //die("sdsds");
        $query = $this->createQueryBuilder('c');
                 $query = $query->getQuery();
        return $query->getResult();
       
        
    }
}
