<?php

namespace AppBundle\Repository;

/**
 * FcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FcRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFc($client_id,$brand_id,$year,$month)
    {
        $query = $this->createQueryBuilder('a');
        $query->select('a.fc');
        $query->where('a.client=  :client_id');
        $query->setParameter('client_id', $client_id);

        $query->andWhere('a.brand=  :brand_id');
        $query->setParameter('brand_id', $brand_id);

        $query->andWhere('a.wMonth=  :wMonth');
        $query->setParameter('wMonth', $month);

        $query->andWhere('a.wYear=  :year');
        $query->setParameter('year', $year);
        $query = $query->getQuery();
        return $query->getOneOrNullResult();
        
    
       
    }

    public function getFcRow($client_id,$brand_id,$year,$month)
    {
        $query = $this->createQueryBuilder('a');
       // $query->select('a.fc');
        $query->where('a.client=  :client_id');
        $query->setParameter('client_id', $client_id);

        $query->andWhere('a.brand=  :brand_id');
        $query->setParameter('brand_id', $brand_id);

        $query->andWhere('a.wMonth=  :wMonth');
        $query->setParameter('wMonth', $month);

        $query->andWhere('a.wYear=  :year');
        $query->setParameter('year', $year);
        $query = $query->getQuery();
        return $query->getOneOrNullResult();
        
    
       
    }

    

}
