<?php

namespace AppBundle\Repository;

/**
 * GeneralThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralThemeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTheme($client_id,$year,$month,$half)
    {
        $query = $this->createQueryBuilder('b');
        //$query->select('b.id,b.name,b.brandOrder,b.imageH');
        $query->setMaxResults(1);
        $query->where('b.client_id =  :client_id');
        $query->setParameter('client_id',$client_id);

        $query->andWhere('b.wYear =  :wYear');
        $query->setParameter('wYear',$year);

        $query->andWhere('b.wMonth =  :wMonth');
        $query->setParameter('wMonth',$month);

        $query->andWhere('b.wHalf =  :wHalf');
        $query->setParameter('wHalf',$half);

        $query = $query->getQuery();
        return $query->getOneOrNullResult();
    }


         //migration 
         public function getCount()
         { 
             return $this->createQueryBuilder('c')->select('count(c.id)')
                           //->setMaxResults(5)
                           //->setFirstResult(11110)
                           ->where('c.flag is Null')
                           //->andWhere('c.WYear = 2010')
                           ->getQuery()
                           
                           ->getSingleScalarResult();
         }
     
         public function getFirstAsArray()
         { 
             return $this->createQueryBuilder('c')
                            ->select('c.id,c.wYear,c.wMonth,c.wHalf,c.themeExtraInfo,c.lastUpdatedBy,
                                      c.lastUpdatedDate,c.client_id,c.theme_id')
                                      ->where('c.flag is NULL')
                                      //->andWhere('c.WYear = 2010')
                                     ->setMaxResults(1)
                                     ->getQuery()
                                     ->getOneOrNullResult();
         }

}
