<?php

namespace AppBundle\Repository;

/**
 * headerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class headerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getheaders()
    {
        $query = $this->createQueryBuilder('a');
        $query->where('c.enable =  1');
        $query = $query->getQuery();
       return  $query->getResult();
      
    }
    public function getByName($name)
    {
        $query = $this->createQueryBuilder('a');
        $query->where('a.name=  :name');
        $query->setParameter('name', $name);
        $query = $query->getQuery();
       return  $query->getOneOrNullResult();
      
    }
    public function getAllByName($key)
    {
        //die("sdsds");
        $query = $this->createQueryBuilder('c');

        $query->where('c.name like :headerName');
        $query->setParameter('headerName', $key . '%');

        $query->andWhere('c.flag !=  1');
        $query->andWhere('c.enable =  1');
        $query = $query->getQuery();
                 
        return $query->getResult();
       
        
    }

    public function getAll()
    {
        //die("sdsds");
        $query = $this->createQueryBuilder('c');

        //$query->where('c.name like :headerName');
        //$query->setParameter('headerName', $key . '%');

        $query->where('c.flag !=  1');
        $query->andWhere('c.enable =  1');
        $query = $query->getQuery();
                 
        return $query->getResult();
       
        
    }
}
