<?php

namespace AppBundle\Repository;
use Symfony\Component\Translation\Translator;
use AppBundle\Entity\Activity;
/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {

        $query = $this->createQueryBuilder('c');
                 $query = $query->getQuery();
        return $query->getResult();
       
        
    }  
    public function getLang($iso)
    {
        return        $this->createQueryBuilder('c')
                            ->where('c.isoName =  :iso') // $query->where('c.id=  :id');
                            ->setParameter('iso', $iso)
                            ->getQuery()
                            ->getOneOrNullResult();
    }

    


}
