<?php

namespace AppBundle\Repository;

/**
 * msImpactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class msImpactRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMsImapact()
    {
        $query = $this->createQueryBuilder('a');
        $query = $query->getQuery();
       return  $query->getResult();
      
    }
    public function getAll()
    {
        //die("sdsds");
        $query = $this->createQueryBuilder('c');
                 $query = $query->getQuery();
        return $query->getResult();
       
        
    }
}
