<?php

namespace AppBundle\Repository;

/**
 * RealDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    { 
        return $this->createQueryBuilder('c')
                     //->setMaxResults(5)
                     ->where('c.flag is Null')
                     // ->setFirstResult(18141)
                      ->getQuery()
                      ->getArrayResult();
    }

    public function getone()
    {
                
        $query = $this->createQueryBuilder('c');
                 $query->setMaxResults(10);
                 $query->where('c.WYear = 2010');
                 $query->andWhere('c.NShops != 0');
                 $query->andWhere('c.NShops4 != 0');
                 $query->andWhere('c.NShops5 != 0');
                // $query->andWhere('c.IDBrand = 22');
                 $query = $query->getQuery();
        return $query->getArrayResult();
    }

    public function getCount()
    { 
        return $this->createQueryBuilder('a')->select('count(a.id)')
                     ->where('a.flag is Null')
                      //->setMaxResults(5)
                      //->setFirstResult(11110)
                      ->andWhere("(
                        a.NShops !='' OR 
                        a.NShops0 !='' OR
                        a.NShops1 !=''  OR
                        a.NShops2 !='' OR 
                        a.NShops3 !='' OR
                        a.NShops4 !='' OR
                        a.NShops5 !='' OR
                        a.NShops6 !='' OR 
                        a.NShops7 !='' OR
                        a.NShops8 !='' OR
                        a.NShops9 !=''
                             )")
                       // ->andWhere('a.WYear = 2019')
                      //->andWhere('a.WYear = 2010')
                      ->getQuery()
                      ->getSingleScalarResult();
    }
    public function getFirst()
    { 
        return $this->createQueryBuilder('c')
                      ->setMaxResults(1)
                      ->where('c.flag is Null')
                      ->getQuery()
                      ->getOneOrNullResult();
    }

    public function getFirstAsArray()
    { 
        return $this->createQueryBuilder('c')
                       ->select('c.id,c.IDClient,c.IDBrand,c.WYear,c.WMonth,c.WHalf,c.NShops,c.NShops0,c.NShops1,c.NShops2,c.NShops3,c.NShops4,c.NShops5,c.NShops6,c.NShops7,c.NShops8,c.NShops9')
                      ->setMaxResults(1)
                      ->where('c.flag is Null')
                      ->andWhere("(
                                    c.NShops  !='' OR 
                                    c.NShops0 !='' OR
                                    c.NShops1 !=''  OR
                                    c.NShops2 !='' OR 
                                    c.NShops3 !='' OR
                                    c.NShops4 !='' OR
                                    c.NShops5 !='' OR
                                    c.NShops6 !='' OR 
                                    c.NShops7 !='' OR
                                    c.NShops8 !='' OR
                                    c.NShops9 !=''
                                         )")
                       // ->andWhere('c.WYear = 2019')
                      //->andWhere('c.WYear = 2009')
                     // ->andWhere('c.WYear = 2010')
                      ->getQuery()
                      ->getOneOrNullResult();
                      
                    //$query->andWhere('a.wYear =  :year AND a.wMonth = :my_month');
                     
    }

           

          

}
