<?php

namespace AppBundle\Repository;

/**
 * UserLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLangRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserLang($id)
    { 
        return $this->createQueryBuilder('c')
                      //->setMaxResults(5)
                     // ->setFirstResult($offset)
                     ->where('c.iDEmpleado =  :id') // $query->where('c.id=  :id');
                     ->setParameter('id', $id)
                     ->getQuery()
                     ->getOneOrNullResult();
    }
}
