<?php

namespace AppBundle\Repository;

/**
 * UserPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPasswordRepository extends \Doctrine\ORM\EntityRepository
{
}
